export interface BrandConfig {
  logoUrl: string | null;
  logoDarkUrl: string | null;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  fontFamily: string;
  reportHeaderText: string;
  reportFooterText: string;
  showQrCode: boolean;
}

export const DEFAULT_BRAND: BrandConfig = {
  logoUrl: null,
  logoDarkUrl: null,
  primaryColor: "#22C55E",
  secondaryColor: "#3B82F6",
  accentColor: "#F59E0B",
  fontFamily: "DM Sans",
  reportHeaderText: "Digital Product Passport Report",
  reportFooterText: "Generated by HelioTrail — EU ESPR Compliant",
  showQrCode: true,
};

export type ExportFormat = "pdf" | "excel";

export interface ExportConfig {
  format: ExportFormat;
  brand: BrandConfig;
  sections?: string[];
}
